# Generated by Django 5.2 on 2025-06-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='attachment',
        ),
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
