# Generated by Django 5.2 on 2025-06-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0002_remove_announcement_attachment_announcement_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='posted_by',
        ),
    ]
