# Generated by Django 5.2 on 2025-07-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0002_alter_announcement_options_announcement_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_active',
        ),
    ]
