# Generated by Django 5.2 on 2025-06-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
