# Generated by Django 5.2 on 2025-06-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalaccount', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='birth_year',
        ),
    ]
