# Generated by Django 5.2 on 2025-06-09 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_rename_created_by_classroom_teacher'),
        ('portalaccount', '0005_alter_parentprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portalaccount.teacherprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalaccount.studentprofile'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portalaccount.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
